version: "3.8"

services:
  backend:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
